### ISSUE TITLE
Hints to improve performance beyond defaults

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/wiki#26]
We could use a new page that describes, how users can improve performance beyond FO's defaults.
Basically it should gather many suggestions we've done in Discord #support into one page.

- Giving more RAM for the instance
- Adjusting video settings
- Taking advantage of external GPU, updating their drivers
- Using additional mods not part of FO (e.g. Phosphor, C2ME)

Originally this issue suggested only giving GPU suggestions, text below:

----

Some users with gaming computers have complained about poor performance with FO. The issue has usually been with the game not using the better GPU as expected.

We might need a wiki page that instructs how to adjust those settings. Since I do not have a gaming computer, I do not have much experience with that, so I cannot start one by myself.

Should be done as a separate page.

**Comment by Madis0** [comment]
Suggestions by @Julienraptor01: 
>with FO Min should be 512MB
Max depending on the usage should be 2GB for light use, 4GB for most users, and 6GB is only if you want to play with shader + high render distance + high res pack etc
 >
> yes minecraft like to have RAM but the Java GC don't like too have too much RAM to clear and putting 8GB or more just make his task very much harder and you are far past the point of diminishing returns where adding more RAM make the situation just worse
>
> The Bot Finder / The Real Bot — Today at 3:26 PM
You should really look at this btw
The Bot Finder / The Real Bot — Today at 3:27 PM
When i mean light use, i mean either light use because you want to or because potato pc btw
For drivers, basically always stay up to date with the programs in /tag name:drivers
And for selecting GPU (on windows) we can show the universal method via the windows settings and via the brand softwares
> I can show win 10 settings and nvidia control panel

**Comment by Madis0** [comment]
https://minecrafthopper.net/help/amd-dedicated-gpu/
via @osfanbuff63

**Comment by Kichura** [comment]
Or the very crazy way: Optimize it yourself by modifying configs not normally accessible by mod menu.

**Comment by Madis0** [comment]
Page added.
