### ISSUE TITLE
Site dark mode

### ISSUE THREAD

**Issue by osfanbuff63** [Fabulously-Optimized/wiki#32]
This might not be possible with the current setup but would love a dark mode for the wiki. It might need to wait for 
Fabulously-Optimized/fabulously-optimized.github.io#1, since *in theory* it wouldn't be too hard to move everything over to that site in a /wiki/ subdirectory or something. But that's a project for the future :P

**Comment by Madis0** [comment]
I wish there was a toggle, but that's on GitBook. https://docs.gitbook.com/spaces/customizing-a-space#theming
Right now there is just either light or dark, and I think light is more readable.
