### ISSUE TITLE
Add language switcher in README.md

### ISSUE THREAD

**Issue by ghost** [Fabulously-Optimized/wiki#60]
Can you add a language switcher in [README.md](https://github.com/Fabulously-Optimized/wiki/blob/main/README.md)?
like this: [Deutsch](https://github.com/Fabulously-Optimized/wiki/tree/main/de-de) | [English (US)](https://github.com/Fabulously-Optimized/wiki/tree/main/en-us) | [Eesti (Eesti)](https://github.com/Fabulously-Optimized/wiki/blob/main/et-ee.md) | [Русский (Russkiy)](https://github.com/Fabulously-Optimized/wiki/blob/main/ru-ru.md)

**Comment by Madis0** [comment]
Hmm. I think people could select the language from the sidebar and then they could see the "table of contents".

Either way, #58 must be thought of as well.

**Comment by Madis0** [comment]
Decided against this per #58
